### ISSUE TITLE
Handling async operations

### ISSUE THREAD

**Issue by dassennato** [chriskrycho/true-myth#18]
Hi there, I'm new with functional programming so maybe this question may looks silly. 
The thing is I recently started using this library, it seems great but I'm not sure how to deal with async operations. 
Well actually after some time reading the docs and other fp stuff I'm realizing that there's no way to handle that with this library and I should use another library, e.g Fluture.

Is that so? I mean, for strict functional programming I have to use Ramda, a monad library like this one and another library for async operations? 
That's a lot of API to learn there 😆

Or maybe I'm missing something and there's a way to do something like this:
```ts
type AsyncResult = Result<string, { readonly reason: string }>;

const asyncA = (): Promise<AsyncResult> => Promise.resolve(Result.ok('A'));
const asyncB = (value: string): Promise<AsyncResult> => Promise.resolve(Result.ok(value + 'B'));
const asyncC = (value: string): Promise<AsyncResult> => Promise.resolve(Result.ok(value + 'C'));

(await asyncA()).flatMap(asyncB).flatMap(asyncC); // Ok('ABC')
```
Thanks in advance!

UPDATE: After some attempts I solved it like this:
```ts
const resultA = await asyncA();
const resultB = resultA.isOk() ? await asyncB(resultA.value) : resultA;
const resultC = resultB.isOk() ? await asyncC(resultB.value) : resultB;
const result = resultC.unwrapOr('');
console.log(result); // 'ABC'
```
But I think there must be a better way...

**Comment by chriskrycho** [comment]
Hi @dassennato – great feedback, and this is definitely something which has come up in my own usage. The patterns you used there are not dissimilar to things I’ve explored. Unfortunately, I haven’t come up with a pattern that works well _in JS_ (there are good patterns in other languages, but I haven’t mapped them back successfully) to compose asynchronous behavior and a Result.

I actually have one type in one of my apps which is `Promise<Result<Result<A, B>, C>>>`. I don’t love it a bit, but it gets the job done.

I also _generally_ end up using `Promise#then` rather than `async`/`await`, though there are definitely tradeoffs each direction.

I’m going to close this because I don’t intend to add anything to the library around this *at this point* – not until I have a better handle on what a good solution might actually look like! – but thank you for using the library and thanks for the thoughtful feedback. And if you come up or stumble across with patterns that work better, please do link them here!
